%% Import data from text file.
% Script for importing data from the following text file:
%
%    I:\My Drive\Product\Data analysis\Analogue devices\second data set\20190320\Comox_data.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/03/20 15:03:24

%% Initialize variables.
filename = 'I:\My Drive\Product\Data analysis\Analogue devices\second data set\20190320\Comox_data_manually_changed.txt';
delimiter = ',';

%% Format string for each line of text:
%   column1: text (%q)
%	column2: text (%q)
%   column3: text (%q)
%	column4: text (%q)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
deviceUid01 = dataArray{:, 1};
timestamp1553028694663 = dataArray{:, 2};
datareading26 = dataArray{:, 3};
assetUid7 = dataArray{:, 4};


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;