%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\MalikAnasAhmad\Downloads\data_warehouse_production.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/09/13 15:02:54

%% Initialize variables.
filename = 'C:\Users\MalikAnasAhmad\Downloads\data_warehouse_production.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%q)
%   column3: datetimes (%{yyyy-MM-dd HH:mm:ss}D)
%	column4: text (%q)
%   column5: text (%q)
%	column6: double (%f)
%   column7: text (%q)
%	column8: text (%q)
%   column9: text (%q)
%	column10: text (%q)
%   column11: double (%f)
%	column12: text (%q)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%q%{yyyy-MM-dd HH:mm:ss}D%q%q%f%q%q%q%q%f%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
id = dataArray{:, 1};
env = dataArray{:, 2};
time = dataArray{:, 3};
session_id = dataArray{:, 4};
activity_session_id = dataArray{:, 5};
sequence_id = dataArray{:, 6};
company_space = dataArray{:, 7};
user_email = dataArray{:, 8};
action = dataArray{:, 9};
platform = dataArray{:, 10};
response_time = dataArray{:, 11};
ip = dataArray{:, 12};

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% time=datenum(time);


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;